# Generated by Django 3.0.4 on 2020-04-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualrecognition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
