# Generated by Django 3.0.4 on 2020-04-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualrecognition', '0002_delete_categorymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityModel',
        ),
    ]
