# Generated by Django 3.0.4 on 2020-04-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualrecognition', '0003_delete_activitymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributesModel',
        ),
    ]
