# Generated by Django 3.0.4 on 2020-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('topic_id', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
