# Generated by Django 3.0.4 on 2020-03-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicactivity',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='topiclocation',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='topicobject',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='topicother',
            options={'ordering': ['tag']},
        ),
    ]
