# Generated by Django 3.0.4 on 2020-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=255)),
                ('word2', models.CharField(max_length=255)),
                ('score', models.FloatField()),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
