# Generated by Django 3.0.4 on 2020-03-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0002_auto_20200309_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicActivity',
        ),
        migrations.DeleteModel(
            name='TopicLocation',
        ),
        migrations.DeleteModel(
            name='TopicObject',
        ),
        migrations.DeleteModel(
            name='TopicOther',
        ),
    ]
