# Generated by Django 3.0.4 on 2020-04-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0002_similaritymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='similaritymodel',
            options={'ordering': ['-score']},
        ),
    ]
