# Generated by Django 3.0.4 on 2020-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retrieval', '0003_auto_20200309_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
    ]
