# Generated by Django 3.0.4 on 2020-03-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0004_topicobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicObject',
        ),
    ]
