# Generated by Django 3.0.4 on 2020-04-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-tag'],
            },
        ),
        migrations.CreateModel(
            name='ConceptScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('box', models.CharField(blank=True, max_length=255)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileupload.ConceptModel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='database/')),
                ('slug', models.SlugField(blank=True)),
                ('minute_id', models.CharField(blank=True, max_length=255)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('concepts', models.ManyToManyField(blank=True, through='fileupload.ConceptScoreModel', to='fileupload.ConceptModel')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255)),
                ('local_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.ImageModel')),
            ],
            options={
                'ordering': ['local_time'],
            },
        ),
        migrations.AddField(
            model_name='conceptscoremodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileupload.ImageModel'),
        ),
    ]
