# Generated by Django 3.0.4 on 2020-03-05 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20200305_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='local_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='minute_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='timezone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='utc_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
