# Generated by Django 3.0.4 on 2020-04-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20200411_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'ordering': ['-tag']},
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='local_time',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='timezone',
        ),
        migrations.CreateModel(
            name='LocationInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timezone', models.CharField(blank=True, max_length=255)),
                ('local_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.ImageModel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.LocationModel')),
            ],
            options={
                'ordering': ['local_time'],
            },
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='location',
            field=models.ManyToManyField(blank=True, through='fileupload.LocationInfoModel', to='fileupload.LocationModel'),
        ),
    ]
