# Generated by Django 3.0.4 on 2020-04-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20200412_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-tag'],
            },
        ),
        migrations.CreateModel(
            name='CategoryScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.CategoryModel')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.ImageModel')),
            ],
        ),
    ]
