# Generated by Django 3.0.4 on 2020-03-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20200305_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='local_time',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='minute_id',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='utc_time',
        ),
    ]
