# Generated by Django 3.0.4 on 2020-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_auto_20200305_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='minute_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
