# Generated by Django 3.0.4 on 2020-04-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_categorymodel_categoryscoremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='categories',
            field=models.ManyToManyField(blank=True, through='fileupload.CategoryScoreModel', to='fileupload.CategoryModel'),
        ),
    ]
