# Generated by Django 3.0.4 on 2020-03-05 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_imagemodel_minute_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
