# Generated by Django 3.0.4 on 2020-04-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20200412_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryscoremodel',
            old_name='category',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='conceptscoremodel',
            old_name='concept',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='locationinfomodel',
            old_name='location',
            new_name='tag',
        ),
    ]
