# Generated by Django 3.0.4 on 2020-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_auto_20200305_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
