# Generated by Django 3.0.4 on 2020-03-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_auto_20200305_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
