# Generated by Django 3.0.4 on 2020-03-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0010_auto_20200305_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fileupload.ImageModel'),
        ),
    ]
