# Generated by Django 3.0.4 on 2020-03-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0013_auto_20200305_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributesmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='conceptmodel',
            name='image',
        ),
        migrations.DeleteModel(
            name='ActivityModel',
        ),
        migrations.DeleteModel(
            name='AttributesModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='ConceptModel',
        ),
    ]
