# Generated by Django 3.0.4 on 2020-03-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0014_auto_20200306_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='name',
            new_name='tag',
        ),
    ]
