# Generated by Django 3.0.4 on 2020-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0015_auto_20200311_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
